# Generated by Django 2.1.2 on 2018-10-29 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('nombres', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=25)),
                ('documento_identidad', models.BigIntegerField()),
                ('fecha_nacimiento', models.DateTimeField()),
                ('correo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('talla_camiseta', models.CharField(max_length=3, null=True)),
                ('estado_persona', models.BooleanField()),
                ('rol_persona', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('tablero', models.CharField(max_length=500)),
                ('tarjeta', models.CharField(max_length=500)),
                ('horas_reportadas', models.FloatField()),
                ('fecha_de_reporte', models.DateTimeField()),
                ('observacion', models.CharField(max_length=1000)),
                ('estado', models.CharField(max_length=500)),
                ('id_Reporte', models.IntegerField(primary_key=True, serialize=False)),
                ('Persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.Persona')),
            ],
        ),
    ]
